image: node:10

before_script:
  - npm install

cache:
  paths:
    - node_modules/

test:
  script:
    - npm run build-lib
    - npm run test

publish:
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - npm run package
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm run publish
