image: weltn24/up-docker-node-chrome-headless:chrome-66_node-10.0_yarn-1.6.0

before_script:
  - npm install

cache:
  paths:
    - node_modules/

test:
  script:
    - npm run build-lib
    - npm run testCI

publish:
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - npm run package
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm run publish
