image: springmedia/rbbt-fnk-docker-node-chrome-headless:chr78-n12.13.0-y1.19.1

before_script:
  - npm install

cache:
  paths:
    - node_modules/

test:
  script:
    - npm run build-lib
    - npm run testCI

publish:
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - npm install -g npm-cli-login
    - npm run package
    - npm-cli-login -u ${NPM_USERNAME} -p ${NPM_PASSWORD} -e nick@bit4bit.at
    - npm run publish
